dupliR
======

This package was implemented to measure the differences in expression and correlation in expression of homoeologs genes along several samples, and to compare these metrics measured in homoeologs regulated as a couple (RAAC genes) by microRNAs and in homoeologs no regulated as a couple (Non-RAAC genes).

This package contains a function that creates a S4 object where the reads counts by gene pair is stored in separate. This function requires a data.frame or matrix with the read counts for every gene normalised by gene length. Rownames should be set with the gene names and column names should be set with the library, samples or treatment names.

Also it is needed to incorporate a character vector with the common names of the pair genes (homoeologs) that were regulated as a couple (RAAC genes) in order to identify them in the dataset.

NOTE: it is important to remember that (homoeologs / duplicates) gene names should be named with a common name followed by .L or .S. In example: commonName.L commonName.S (ntf23.L and ntf23.S). The character vector of the common names of the RAAC genes should be without .L or .S (just the commonName).

---

## Objects

This package contains S4 objects to separate by duplicates / homoeologs pairs and store a dataset of read counts normalised by gene length.

The class object "pair" has two slots, one for gene name (character) and the another for store a data.frame with the read counts of both duplicates or homoeologs. rownames are the name of each gene, and columnames are the library (SRR) name or treatment name.

The class object "pairList" contains two slots: one slot to store the gene name (require an object "ExpMet"), and the second slot is used to store a list object, so you can append indefinitely number of "pair" objects in this slot.

In addition, this package has also a "ExpMet" object and is used to store all Experiment metadata needed to track the experiment where the libraries come from. Currently, this object has only one slot called ExpName (character).

NOTE: every duplicate or homoeolog pair should be marked exclusively by .L or .S at the end of the gene name, and the common gene name should be the same

example: if the name of the gene is ntf23 the duplicates genes should be named like ntf23.L and the copy ntf23.S

## Methods

- DET(): creates the duplicates / homoeologs expression table (DET) object
- calDif(): calculates the difference in expression level (read counts normalised by gene length) between duplicates / homoeologs
- calCor(): calculates the Pearson correlation of expression level between a pair of genes along treatments (libraries)
- plotWTPV(): plots the Wilcoxon test p-value
- plotCor(): plots the Pearson correlation coefficient

## Examples
In this package there are a naive dataset of normalised read counts and a character vector with the hypothetical common names of RAAC genes. In order to use them you can load them with data().  
data(exp)  
data(raac)  

First of all, we have to create the DET object.  
det <- DET(exp)  

Then we can calculate differences in expression and the Pearson correlation.  
dif <- calDif(det, raac)  
corr <- calCor(det, raac)  

Finally, we can plot the results with the following functions.  
plotWTPV(dif)  
plotCor(corr)  

These functions will create two files WTPV.pdf and RAAC_correlation.pdf
